on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger singleJob
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.sdpmlab.org/"
        user: "czhuang"
        token: ${{ secrets.TOKEN}}
        job: "tcse2023410877023"
  
