on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger singleJob
      uses: appleboy/jenkins-action@master
      with:
        url: "http://127.0.0.1:8080/"
        user: "czhuang"
        token: ${{ secrets.TOKEN }}
        job: "myFstJenkinsPrj"
  
